os: linux
sudo: required
dist: trusty

services:
  - docker

before_install:
    docker pull kremius/cpp-board-engine-build;

script:
    docker run -v $TRAVIS_BUILD_DIR:/app
    -e TRAVIS
    -e TRAVIS_REPO_SLUG
    -e TRAVIS_JOB_ID
    -e TRAVIS_PULL_REQUEST
    -e TRAVIS_BRANCH
    -e COVERALLS_TOKEN
    kremius/cpp-board-engine-build /app/build-in-docker.sh;
